export const quizzes = [
  { id: 0, name: 'elephant' },
  { id: 1, name: 'Baran' },
  { id: 2, name: 'tiger' },
  { id: 3, name: 'lion' },
  { id: 4, name: 'giraffe' },
  { id: 5, name: 'zebra' },
  { id: 6, name: 'panda' },
  { id: 7, name: 'koala' },
  { id: 8, name: 'kangaroo' },
  { id: 9, name: 'rabbit' },
  { id: 10, name: 'fox' },
  { id: 11, name: 'bear' },
  { id: 12, name: 'deer' },
  { id: 13, name: 'wolf' },
  { id: 14, name: 'eagle' },
  { id: 15, name: 'dolphin' },
  { id: 16, name: 'whale' },
];
